version: '3.5'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data
      - ./docker-entrypoint:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pwd
    networks:
      - stackoverflow-light-net

networks:
  stackoverflow-light-net:
    driver: bridge
    name: stackoverflow-light-net
